name = "the-hunt-mods"
author = "Bryan Honof"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c06a1c67a46c95bd54284f96f5df01c2abfc8b0669b51d67b5238925342b96d5"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"
