name = "the-hunt-mods"
author = "Bryan Honof"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "377c24a44395803239c09257953175b34bf060125a97d6b9c5a1c71f9a68e902"

[versions]
fabric = "0.16.13"
minecraft = "1.21.4"
