name = "the-hunt-mods"
author = "Bryan Honof"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "530ef29e67bd97982da7bb04931fcee0d1675bee02cd15f1fa86dc39e2332a48"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
